version: '3.3'
services:
  firestore-emulator:
    image: mtlynch/firestore-emulator:latest
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_PROJECT_ID=local-test-project
      - PORT=8080

  bigquery-emulator:
    image: ghcr.io/goccy/bigquery-emulator:latest
    ports:
      - "9050:9050"
    environment:
      - BIGQUERY_PROJECT_ID=local-test-project
      - BIGQUERY_DATASET_ID=ocr_data
    command: --project local-test-project --dataset ocr_data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
      - BIGQUERY_EMULATOR_HOST=bigquery-emulator:9050
      - GOOGLE_CLOUD_PROJECT=local-test-project
      # 開発環境用の認証設定
      - GOOGLE_APPLICATION_CREDENTIALS=/app/test-credentials.json
    volumes:
      - ./backend:/app
      # 開発環境用の認証情報をマウント
      - ./backend/test-credentials.json:/app/test-credentials.json:ro
    depends_on:
      - firestore-emulator
      - bigquery-emulator
